# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('nickname', models.CharField(default='jack', max_length=32, verbose_name='昵称')),
                ('phonenum', models.CharField(max_length=11, verbose_name='手机')),
                ('birthday', models.DateField(default='2000-01-1', verbose_name='生日')),
                ('gender', models.CharField(default='male', max_length=6, verbose_name='性别')),
                ('location', models.CharField(default='北京', max_length=32, verbose_name='常居地')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SmallIntegerField(verbose_name='关联User键')),
                ('dating_gender', models.CharField(default='female', max_length=6, verbose_name='匹配的性别')),
                ('dating_location', models.CharField(default='北京', max_length=16, verbose_name='目标城市')),
                ('max_distance', models.FloatField(default='10', verbose_name='最大查找范围')),
                ('min_distance', models.FloatField(default='1', verbose_name='最小查找范围')),
                ('max_dating_age', models.SmallIntegerField(default='80', verbose_name='最大交友年龄')),
                ('min_dating_age', models.SmallIntegerField(default='20', verbose_name='最小交友年龄')),
                ('vibration', models.BooleanField(default=False, verbose_name='开启震动')),
                ('only_matched', models.BooleanField(default=False, verbose_name='不让未匹配的人看我的相册')),
                ('auto_play', models.BooleanField(default=False, verbose_name='自动播放视频')),
            ],
        ),
    ]
