# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='', max_length=256, verbose_name='个人头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='male', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('成都', '成都'), ('深圳', '深圳')], default='北京', max_length=32, verbose_name='常居地'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(db_index=True, default='jack', max_length=32, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenum',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机'),
        ),
    ]
