# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200722_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.SmallIntegerField(unique=True, verbose_name='关联User键'),
        ),
    ]
